### ISSUE TITLE
Secure sessions non happy path checklist

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/ide-ext-vscode#78]
- [ ] For when BioID enrollment api request fails
- [ ] For when BioID verification api request fails
- [ ] For when BioID verification fails (not the API failing, but when the verification from BioID is not a success - indicating that the user captured is NOT the one that enrolled)

**Comment by cwdcwd** [comment]
I think we kill the session with an error  for those unchecked ones except the API failure
